### ISSUE TITLE
Unexpected token ;

### ISSUE THREAD

**Issue by ghost** [charredgrass/nodejs-bot-guide#4]
I'm, having problems when i try to run the login.js. If i remove the line of twoFactorCode on the logOnOptions i have no problems but i can't login in. 

Changed 'twoFactorCode' to "twoFactorCode" and still with this error. 

[http://i.imgur.com/MJI142g.jpg](url)

**Comment by charredvenge** [comment]
I had a typo in my code, sorry! Remove the semicolon after the parentheses on line 12 and it should work.
