### ISSUE TITLE
How secure is this?

### ISSUE THREAD

**Issue by User4469** [charredgrass/nodejs-bot-guide#5]
Im quite new to this and my bot is working fine, but you do have to enter your steam username and password in the script, is there any way someone can get your password during the process of your bot communicating with steam or something like that? How secure is this method?

**Comment by charredvenge** [comment]
You are correct - the password being in plain text is a security risk - but **only** if someone else has access to your computer or the bot file. When logging into Steam the bot acts just like a Steam client or Web browser would, so your password is secure, but be careful when storing your password in a vulnerable location in plaintext.
